name: weak-tie-opp-structure
channels:
  - conda-forge
dependencies:
  - python=3.11
  - osmnx>=1.8,<2.0
  - geopandas>=0.14,<0.15
  - networkx>=3.2,<4.0
  - pandas>=2.1,<2.3
  - numpy>=1.26,<2.0
  - shapely>=2.0,<2.1
  - rtree>=1.1,<1.2
  - pyproj>=3.6,<3.8
  - fiona>=1.9,<2.0
  - contextily>=1.3,<1.5
  - matplotlib>=3.8,<3.9
  - folium>=0.15,<0.17
  - branca>=0.6,<0.7
